# Generated by Django 3.2 on 2023-08-25 07:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sms',
            name='contact',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='home.contact'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='voicemail',
            name='contact',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='home.contact'),
            preserve_default=False,
        ),
    ]
