# Generated by Django 3.2 on 2023-10-25 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_note'),
    ]

    operations = [
        migrations.AlterField(
            model_name='creditcard',
            name='card_holder_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
