# Generated by Django 3.2 on 2023-08-27 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_contact_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sms',
            name='contact',
        ),
        migrations.AddField(
            model_name='sms',
            name='contact',
            field=models.ManyToManyField(to='home.Contact'),
        ),
        migrations.RemoveField(
            model_name='voicemail',
            name='contact',
        ),
        migrations.AddField(
            model_name='voicemail',
            name='contact',
            field=models.ManyToManyField(to='home.Contact'),
        ),
    ]
