# Generated by Django 3.2 on 2023-11-17 17:27

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_profile_is_credit_card_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unique_code', models.CharField(blank=True, max_length=100)),
                ('date_generated', models.DateTimeField(default=django.utils.timezone.now)),
                ('expiring_date', models.DateTimeField()),
            ],
        ),
    ]
