# Generated by Django 3.2 on 2023-09-25 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_contact_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='creditcard',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
