# Generated by Django 3.2 on 2023-11-25 01:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('home', '0006_emailcode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sms',
            name='sms_text',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sms',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sms_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
