# Generated by Django 3.2 on 2023-11-25 02:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('home', '0007_auto_20231125_0158'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sms',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sms_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
